#ifndef OS_CONSTANT_H
#define OS_CONSTANT_H

#define IDT_START_ADDRESS 0x8880
#define CODE_SELECTOR 0x20
#define MAX_PROGRAM_NAME 16
#define MAX_PROGRAM_AMOUNT 16

#define MEMORY_SIZE_ADDRESS 0x7c00
#define PAGE_SIZE 4096

#endif